# This is defaut username and passowrd.
# Use your own in your apps/appName/config/app.yml for prod.

dev:
  sf_simple_auth:
    username:                 username
    password:                 password
    encryption:               ~
# sha1('password')
test:
  sf_simple_auth:
    username:                 username
    password:                 5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8
    encryption:               sha1
