# This is defaut username and passowrd.
# Use your own in your apps/appName/config/app.yml for prod.

dev:
  sf_simple_auth:
    username:                 username
    password:                 password
    encryption:               ~

test:
  sf_simple_auth:
    username:                 username
    password:                 password
    encryption:               ~
