dev:
  sf_simple_auth:
    username:                 username
    password:                 password
    encryption:               ~

test:
  sf_simple_auth:
    username:                 username
    password:                 password
    encryption:               ~
