# This is defaut username and passowrd.
# Use your own in your apps/appName/config/app.yml for prod.

dev:
  sf_simple_auth:
    username:                 username
    password:                 password
    encryption:               ~
    template:                 ~

# sha1('password')
# template is not avaible in plugin. Override it in your project for tests.
test:
  sf_simple_auth:
    username:                 username
    password:                 5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8
    encryption:               sha1
    template:                 [global,mysignin]