# default routing.

sf_simple_auth_signin:
  url:    /signin
  param:  { module: sfSimpleAuth, action: signin }

sf_simple_auth_signout:
  url:    /signout
  param:  { module: sfSimpleAuth, action: signout }
